language: node_js
node_js:
  - "0.10"
after_success:
- ./node_modules/.bin/jscoverage lib lib-cov
- USE_CODE_COVERAGE=true ./node_modules/.bin/mocha test -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
